export const FETCH_USERS = 'FETCH_USERS'
export const USERS_RESET_STATE = 'USERS_RESET_STATE'

export const FETCH_POSTS = 'FETCH_POSTS'
export const POSTS_RESET_STATE = 'POSTS_RESET_STATE'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const COMMENTS_RESET_STATE = 'COMMENTS_RESET_STATE'

export const FETCH_ALBUMS = 'FETCH_ALBUMS'
export const ALBUMS_RESET_STATE = 'ALBUMS_RESET_STATE'

export const FETCH_PHOTOS = 'FETCH_PHOTOS'
export const PHOTOS_RESET_STATE = 'PHOTOS_RESET_STATE'
